### ISSUE TITLE
Consider adding blueprint.json to enable plugin previews

### ISSUE THREAD

**Issue by mrwweb** [devcollaborative/editor-handbook#14]
The fairly recent plugin previews feature in the WP.org repo is pretty awesome and this is a perfect plugin for the feature. [Here's the handbook page on adding it](https://developer.wordpress.org/plugins/wordpress-org/previews-and-blueprints/). Arguably, the absolute simplest possible `blueprint.json` would work for this, since I personally can't think of much I'd want done to a new install beyond installing and activating the plugin and then dumping me onto the Handbook page.

**Comment by hbrok** [comment]
blueprint.json has been added!
